stages:
  - deploy

pages:
  image: openjdk:jre
  stage: deploy
  only:
    - master
  script:
    - sed -i "s/{{git-rev}}/${CI_BUILD_REF:0:7}/" service-worker.js
    - wget http://dl.google.com/closure-compiler/compiler-latest.zip
    - unzip -o compiler-latest.zip
    - mv closure*.jar compiler.jar
    - chmod u+x compiler.jar
    - mkdir -p public
    - java -jar compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS --js_output_file=public/app.js app.js
    - java -jar compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS --js_output_file=public/service-worker.js service-worker.js
    - mv index.html public/
    - mv license.html public/
    - mv LICENSE public/
    - mv default.css public/
    - mv manifest.json public/
    - mv icons/128.ico public/favicon.ico
    - mv icons public/
    - find public -name \*.\* -print
  artifacts:
    paths:
      - public
