# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see https://creativecommons.org/publicdomain/zero/1.0/


stages:
  - deploy

pages:
  image: node:latest
  stage: deploy
  only:
    - master
  script:
    # install stuff
    - apt-get -qq update
    - apt-get install -qq -y imagemagick build-essential git zip unzip
    - npm install -g typescript
    # update hardcoded git tags
    - sed -i "s/{{git-rev}}/$(git describe --tags --always)/" service-worker.ts
    - sed -i "s/{{git-rev}}/$(git describe --tags --always)/g" index.html
    # download and compile Google Zopfli
    - wget https://github.com/google/zopfli/archive/master.zip
    - unzip -o *master.zip
    - pushd zopfli*
    - make zopflipng
    - mv zopflipng ../
    - popd
    # set up the environment
    - mkdir -p public
    # build the scripts
    - tsc
    # convert our base SVG into many PNG files
    - convert -background none icons/base.svg -resize x16 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/16.png # all
    - convert -background none icons/base.svg -resize x32 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/32.png # apple
    - convert -background none icons/base.svg -resize x36 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/36.png # google
    - convert -background none icons/base.svg -resize x48 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/48.png # google
    - convert -background none icons/base.svg -resize x64 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/64.png
    - convert -background none icons/base.svg -resize x70 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/70.png # microsoft
    - convert -background none icons/base.svg -resize x72 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/72.png # google
    - convert -background none icons/base.svg -resize x96 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/96.png # google
    - convert -background none icons/base.svg -resize x128 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/128.png
    - convert -background none icons/base.svg -resize x144 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/144.png # google, microsoft, apple
    - convert -background none icons/base.svg -resize x150 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/150.png # microsoft
    - convert -background none icons/base.svg -resize x180 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/180.png # apple
    - convert -background none icons/base.svg -resize x192 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/192.png # google
    - convert -background none icons/base.svg -resize x256 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/256.png
    - convert -background none icons/base.svg -resize x310 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/310.png # microsoft
    - convert -background none icons/base.svg -resize x512 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/512.png # google
    # compress everything with Google Zopfli
    - ./zopflipng -ym --prefix=zopfli_ --lossy_8bit icons/*.png
    - rename -f "s/zopfli_//" icons/*.png
    # convert base SVG into ico
    - convert -background none icons/base.svg -define icon:auto-resize=16,32,48 public/favicon.ico
    # move our assets in the public folder
    - mv *.html public/
    - mv *.js public/
    - mv *.ts public/
    - mv *.map public/
    - mv LICENSE public/
    - mv *.css public/
    - mv manifest.json public/
    - mv browserconfig.xml public/
    - mv icons public/
    - mv robots.txt public/
    # list public files recursively
    - find public -name \*.\* -print
  artifacts:
    paths:
      - public
