stages:
  - deploy

pages:
  image: openjdk:jre
  stage: deploy
  only:
    - master
  script:
    - apt-get -qq update
    - apt-get install -qq -y imagemagick
    - sed -i "s/{{git-rev}}/${CI_BUILD_REF:0:7}/" service-worker.js
    - sed -i "s/{{git-rev}}/${CI_BUILD_REF:0:7}/g" index.html
    - wget http://dl.google.com/closure-compiler/compiler-latest.zip
    - unzip -o compiler-latest.zip
    - mv closure*.jar compiler.jar
    - chmod u+x compiler.jar
    - mkdir -p public
    # compile the javascript files with Google Closure
    - java -jar compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS --js_output_file=public/app.js app.js
    - java -jar compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS --js_output_file=public/service-worker.js service-worker.js
    # convert our base SVG into many PNG files
    - convert -background none icons/base.svg -resize x16 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/16.png # all
    - convert -background none icons/base.svg -resize x32 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/32.png # apple
    - convert -background none icons/base.svg -resize x36 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/36.png # google
    - convert -background none icons/base.svg -resize x48 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/48.png # google
    - convert -background none icons/base.svg -resize x64 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/64.png
    - convert -background none icons/base.svg -resize x70 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/70.png # microsoft
    - convert -background none icons/base.svg -resize x72 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/72.png # google
    - convert -background none icons/base.svg -resize x96 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/96.png # google
    - convert -background none icons/base.svg -resize x128 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/128.png
    - convert -background none icons/base.svg -resize x144 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/144.png # google, microsoft, apple
    - convert -background none icons/base.svg -resize x150 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/150.png # microsoft
    - convert -background none icons/base.svg -resize x180 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/180.png # apple
    - convert -background none icons/base.svg -resize x192 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/192.png # google
    - convert -background none icons/base.svg -resize x256 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/256.png
    - convert -background none icons/base.svg -resize x310 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/310.png # microsoft
    - convert -background none icons/base.svg -resize x512 -define png:compression-filter=2 -define png:compression-level=9 -define png:compression-strategy=1 icons/512.png # google
    # convert base SVG into ico
    - convert -background none icons/base.svg -define icon:auto-resize=16,32,48 public/favicon.ico
    # move our assets in the public folder
    - mv index.html public/
    - mv license.html public/
    - mv LICENSE public/
    - mv default.css public/
    - mv manifest.json public/
    - mv browserconfig.xml public/
    - mv icons public/
    # list public files recursively
    - find public -name \*.\* -print
  artifacts:
    paths:
      - public
